name: Build on Linux

on:
  push:
    branches: [ "devel", "master" ]
  pull_request:
    branches: [ "devel", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo
  DRUMSTICKNAME: DrumstickV2
  DRUMSTICK_LOCATION: ${{github.workspace}}/DrumstickV2
  UCHARDETNAME: Uchardet008
  UCHARDET_LOCATION: ${{github.workspace}}/Uchardet008

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dawidd6/action-download-artifact@v7
      with:
        name: ${{env.DRUMSTICKNAME}}
        github_token: ${{secrets.GH_PAT}}
        repo: pedrolcl/drumstick
        workflow: cmake.yml
        allow_forks: false

    - name: Extract downloaded files
      run: tar xvf ${{env.DRUMSTICKNAME}}.tar

    - uses: dawidd6/action-download-artifact@v7
      with:
        name: ${{env.UCHARDETNAME}}
        github_token: ${{secrets.GH_PAT}}
        repo: pedrolcl/uchardet
        workflow: linux-build.yml
        allow_forks: false

    - name: Extract downloaded files
      run: tar xvf ${{env.UCHARDETNAME}}.tar

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.*'
        modules: qt5compat

    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install -yq pkg-config libasound2-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
        -DBUILD_DOCS=OFF
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_PREFIX_PATH="${{env.DRUMSTICK_LOCATION}};${{env.UCHARDET_LOCATION}}"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
